- name: clone the external-storage repo
  git: repo=https://github.com/kubernetes-incubator/external-storage.git dest=/root/external-storage

- name: put /root/storageclass.yml
  template: src=storageclass.yml dest=/root/storageclass.yml

- name: create a storageclass
  shell: kubectl apply -f /root/storageclass.yml

- name: put /root/custom-values.yaml
  template: src=custom-values.yaml dest=/root/custom-values.yaml

- name: create /var/lib/k8s/{{ storage_class_name }}
  file: dest=/var/lib/k8s/{{ storage_class_name }} state=directory

- name: create /var/lib/k8s/{{ storage_class_name }}volumes
  file: dest=/var/lib/k8s/{{ storage_class_name }}/{{ item }} state=directory
  with_items: "{{ k8s_local_storage_pv_names }}"

- name: generate a provisioner YAML
  shell: cd /root/external-storage/local-volume && helm template ./helm/provisioner --values /root/custom-values.yaml > /root/provisioner_generated.yaml

- name: create a provisioner
  shell: kubectl apply -f /root/provisioner_generated.yaml
